import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useDispatch,useSelector } from 'react-redux'
import { changeList,removeList } from '../src/store/store'
import { useState } from 'react'
import Link from 'next/link'


export default function Home() {
  let [text,setText]=useState("")
  let {user}=useSelector((state)=>{
    return state;
  })
  let dispatch=useDispatch()
  let handleText=(event)=>{
    setText(event.target.value)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h2>ToDos</h2>
        <input type="text" onChange={handleText} value={text}/>
        <button onClick={()=>{dispatch(changeList(text))}}>추가</button>
        <ul>
         {user.map((elem,index)=>{
           return(
             <div key={index}>
             <li >
               <Link href={`/post/${elem}`}><a>{elem}</a></Link>
             </li>
             <button onClick={ ()=>{dispatch(removeList(elem))}}>삭제</button>
             </div>
           )
         })}
        </ul>

      </div>
    </div>
  )
}
